### ISSUE TITLE
[tauri:dev] Waiting for your dev server to start...

### ISSUE THREAD

**Issue by aliscie** [n8jadams/tauri-typescript-react-boilerplate#34]
it keep returning `[tauri:dev] Waiting for your dev server to start...` for ever

**Comment by n8jadams** [comment]
Can you tell me a little more info about how you got this message?

What operating system are you running on?
Which command did you run?

It's not immediately obvious to me where this message is being logged and I'll need more info to dig deeper.

**Comment by AlenSci** [comment]
- Thank you for your response Nate I solved this issue
- I was running `tauri dev` but I had to run two commands `react-scripts start` then `tauri dev`
-  You may need to **update the readme file**
* **Can you add more functions in the repo so people can learn more from it**
   *  for example how to customize the frame and How to CRUD files.

**Comment by n8jadams** [comment]
In the README I recommend running `yarn dev` or `npm run dev`, which will run `tauri dev` concurrently with the front-end build.

As for adding more functions to the repo, that's more of a Tauri concern than a Tauri boilerplate concern. I recommend just checking out the Tauri docs at https://tauri.studio/ and joining their Discord chat if you need any more support.

In any case, thanks for using the boilerplate! I hope it has been helpful!

**Comment by Wegt-meoh** [comment]
@aliscie @n8jadams @AlenSci 
I'm having the same problem, which is not using _create-tauri-app_ build frontend project and rust project with bare hand.I solved the problem by modify **dev_path port** in _tauri.conf.json_ file.

Ensure that the following two ports are same.
![image](https://user-images.githubusercontent.com/61854272/213935309-4b6229c0-d1d8-4612-9008-964d4eece546.png)

![image](https://user-images.githubusercontent.com/61854272/213935357-baead192-b934-4660-9189-7239743e9302.png)

**Comment by tangramor** [comment]
I met the same problem on MacOS, and the same code works well on Ubuntu.
I managed to make it work to modify the **package.json**:
`"dev": "vite",` to `"dev": "vite --host",`
